---
name: TorrServer
version: 0.2.7
slug: torrserver
description: TorrServer for home assistant
url: https://github.com/Handrace/hassio-torrserver
codenotary: aatrubilin@gmail.com
webui: http://[HOST]:[PORT:8090]
init: false
auth_api: true
arch:
  - armv7
  - amd64
  - i386
ports:
  8090/tcp: 8090
ports_description:
  8090/tcp: TorrServer Web
map:
  - share:rw
options:
  debug: false
schema:
  debug: bool
